# Generated by Django 3.1.5 on 2021-04-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210403_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='horario_disponiveis',
            field=models.TimeField(max_length=5),
        ),
    ]
